version: 2
updates:
  # Enable version updates for npm (Frontend - Renthub)
  - package-ecosystem: "npm"
    directory: "/Renthub"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "anemettemadsen33"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    groups:
      # Group minor and patch updates together
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for Composer (Backend)
  - package-ecosystem: "composer"
    directory: "/Rental-Platform-main/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "anemettemadsen33"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    groups:
      # Group minor and patch updates together
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "anemettemadsen33"
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "chore(ci):"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/Rental-Platform-main/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "anemettemadsen33"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker):"
      include: "scope"
