services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rental_platform_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rental_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Meilisearch (Self-hosted Search Engine)
  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: rental_platform_search
    environment:
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: true
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rental_platform_backend
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: rental_platform
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      QUEUE_CONNECTION: database
      MAIL_MAILER: log
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  meilisearch_data:
